"""Đồng bộ backend/WiFi cho firmware; Android chỉ nhận địa chỉ backend."""

import argparse
import json
from pathlib import Path
import re


PROJECT_ROOT = Path(__file__).resolve().parent
CONFIG_PATH = PROJECT_ROOT / "backend_config.json"


def sync_backend_config(check=False):
    config = json.loads(CONFIG_PATH.read_text(encoding="utf-8"))
    host = config.get("host")
    port = config.get("port")
    wifi_ssid = config.get("wifi_ssid")
    wifi_password = config.get("wifi_password")
    # Chặn cấu hình lỗi trước khi sinh literal C++ hoặc đóng gói Android.
    if not isinstance(host, str) or not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9.-]*", host):
        raise ValueError("host phải là IP hoặc hostname, không gồm http:// hay đường dẫn")
    if type(port) is not int or not 1 <= port <= 65535:
        raise ValueError("port phải là số nguyên từ 1 đến 65535")
    # Cho phép để trống khi chưa cấu hình; không in giá trị WiFi trong thông báo lỗi.
    for key, value in (("wifi_ssid", wifi_ssid), ("wifi_password", wifi_password)):
        if not isinstance(value, str) or any(ord(char) < 32 for char in value):
            raise ValueError(f"{key} phải là chuỗi không chứa ký tự điều khiển")

    header = (
        "// Generated by sync_backend_config.py; edit backend_config.json only.\n"
        "#ifndef SMART_PARKING_BACKEND_CONFIG_H\n"
        "#define SMART_PARKING_BACKEND_CONFIG_H\n"
        "#include <stdint.h>\n\n"
        "namespace BackendConfig {\n"
        f"    constexpr char HOST[] = {json.dumps(host)};\n"
        f"    constexpr uint16_t PORT = {port};\n"
        # Giữ UTF-8 và escape dấu nháy/backslash để literal C++ không bị hỏng.
        f"    constexpr char WIFI_SSID[] = {json.dumps(wifi_ssid, ensure_ascii=False)};\n"
        f"    constexpr char WIFI_PASSWORD[] = {json.dumps(wifi_password, ensure_ascii=False)};\n"
        "}\n\n"
        "#endif\n"
    )
    # Mỗi sketch giữ header cục bộ để không phụ thuộc include ngoài sketch Arduino.
    outputs = {
        PROJECT_ROOT / "src/config/backend_config.h": header,
        PROJECT_ROOT / "esp32cam_entry/backend_config.h": header,
        PROJECT_ROOT / "esp32cam_exit/backend_config.h": header,
        # Tuyệt đối không đưa SSID/mật khẩu vào asset Android.
        PROJECT_ROOT / "android/app/src/main/assets/backend_config.json":
            json.dumps({"host": host, "port": port}, indent=2) + "\n",
    }
    stale = []
    for path, content in outputs.items():
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            if check:
                stale.append(str(path.relative_to(PROJECT_ROOT)))
            else:
                path.write_text(content, encoding="utf-8", newline="\n")
    if stale:
        raise ValueError("Cấu hình chưa đồng bộ: " + ", ".join(stale))
    return f"http://{host}:{port}"


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Chỉ kiểm tra, không ghi file")
    args = parser.parse_args()
    print(sync_backend_config(check=args.check))
